### ISSUE TITLE
Plugin not Working on Ubuntu 18.04 

### ISSUE THREAD

**Issue by GravelCZLP** [KazeJiyu/eclipse-discord-integration#39]
The plugin does not work for me, even if i restart Eclipse and reinstall the plugin, restart and reinstall discord, or even add Eclipse manually.
All i see is https://www.imgup.cz/images/2018/07/02/Snimek-z-2018-07-02-23-43-14.png

**Comment by KazeJiyu** [comment]
Can you open the _Error Log_ view (Window > Preferences > Error Log) and tell me if you see a message that could be relevant ?

**Comment by GravelCZLP** [comment]
No, there are no errors related to this plugin.
I am using Eclipse Photon Release (4.8.0)

**Comment by GravelCZLP** [comment]
Soo, i just tried it in a Linux Mint VM and it worked, soo, it has to be something with my Distro.

**Comment by KazeJiyu** [comment]
It works as expected on Kubuntu 18.04 with Eclipse Oxygen. I guess it should work fine on Ubuntu 18.04 but I cannot test it for the moment.

Please keep me in touch if you find more about your issue.

**Comment by GravelCZLP** [comment]
Well, i switched from Ubuntu to Linux Mint and it works, i accidentally deleted my files in the process. (It is my fault) At least the plugin works now :D
