### ISSUE TITLE
Discord not updated when launched after Eclipse IDE

### ISSUE THREAD

**Issue by KazeJiyu** [KazeJiyu/eclipse-discord-integration#42]
When Discord is launched after Eclipse IDE it is not notified when the selected editor changes.

This is because the connection with Discord is initiated only once: at Eclipse IDE startup.

The issue could be solved by:
- (when not connected) re-trying to connect to Discord each time the active editor changes,
- allowing the user to attempt to create a new connection (e.g. with a dedicated button).

**Comment by KazeJiyu** [comment]
Why ? Don't you have the issue ?

**Comment by KazeJiyu** [comment]
Indeed, I didn't noticed before but it seems that after some time Discord is actually updated. However, I'll keep the issue opened until this behavior is controlled.

**Comment by File14** [comment]
The issue has been solved. The latest version works perfectly.

**Comment by KazeJiyu** [comment]
After a look at Discord RPC's source code it seems that the library manages that on its own. I'll close the issue.
