### ISSUE TITLE
*.h Files not displayed correctly...

### ISSUE THREAD

**Issue by XLPmc** [KazeJiyu/eclipse-discord-integration#48]
Hi!

I'm using eclipse on Linux (OpenSuse Tumbleweed 20180815)
When I'm developing in C++, .h files aren't properly displayed (not as cpp nor as c)

Maybe add an Image for c/cpp header files or ability to select if its displayed as cpp or c
![screenshot_20180820_203442](https://user-images.githubusercontent.com/13018470/44359579-95dc9880-a4b8-11e8-9f55-8dc17360db45.png)

Plugin works well besides that thing ^^

Thanks for Helping!

**Comment by KazeJiyu** [comment]
Hello!

Indeed, I didn't take the time yet to add support for the C language. I should be able to fix this today, though. The language is currently determined according to the extension of the file, so the result should be as follows:

| File extension | Language shown in Discord |
| :-----: | :------: |
| c, h | C |
| cpp, hpp | C++ |

Would it suits your need ?

**Comment by XLPmc** [comment]
Yeah it would pretty much...
but an option to set the display of *.h files to C++ would be nice, because a lot of C++ Projects use *.h files as headers instead of *.hpp files

**Comment by KazeJiyu** [comment]
Yes, I understand your point. I'll think about the best way to specify this option.

I'll close this issue as soon as the icon for the C language is available (which should be done by the end of the week) and I'll create a new issue dedicated to the implementation of this option.

**Comment by KazeJiyu** [comment]
The C language (_*.c_ and _*.h_ files) will be handled in the next 1.0.0 release. I'll provide a way to specify that _*.h_ files are written in C++ as soon as possible.
