### ISSUE TITLE
Eclipse no get closed completely

### ISSUE THREAD

**Issue by CleusGamer201** [KazeJiyu/eclipse-discord-integration#55]
when I close eclipse I get that in my discord game that I'm playing Eclipse when I've already closed it, I checked the windows task manager and it goes out an open eclipse process, it does not close completely when leaving, please fix it <3

**Comment by Clem-Fern** [comment]
I have the same problem too, but only with Windows 7.

**Comment by KazeJiyu** [comment]
Hello, sorry for the late reply !

A similar bug as already been encountered (see #36), but it should be fixed as of `v0.8.4`. Can you confirm that you are using plug-in's latest version (`1.0.0`) ?

Moreover, is this bug occurring every time, or only randomly ?

**Comment by CleusGamer201** [comment]
> Hello, sorry for the late reply !
> 
> A similar bug as already been encountered (see #36), but it should be fixed as of `v0.8.4`. Can you confirm that you are using plug-in's latest version (`1.0.0`) ?
> 
> Moreover, is this bug occurring every time, or only randomly ?

every time, i will try #36 and write again if works or not!

**Comment by CleusGamer201** [comment]
Hello, if I have the latest version (1.0.0) and the same happens every time I open eclipse and when I finish working on eclipse and close it, the discord status and the eclipse process remain open in the task manager in windows 7
![image](https://user-images.githubusercontent.com/17212107/48917813-7eba9780-ee67-11e8-9785-5bd9376580cf.png)

**Comment by KazeJiyu** [comment]
That's strange. Could you give me the exact version of your Eclipse IDE (_Help > About Eclipse IDE_) ?

This might be related to Windows 7 but it would be very surprising ; sadly I cannot test it for the moment.

**Comment by Clem-Fern** [comment]
I just tried on windows 7, it happens with the three versions that I have (Oxygen / Photon / 2018-09).

**Comment by CleusGamer201** [comment]
> That's strange. Could you give me the exact version of your Eclipse IDE (_Help > About Eclipse IDE_) ?
> 
> This might be related to Windows 7 but it would be very surprising ; sadly I cannot test it for the moment.

i use Eclipse 2018-09
![image](https://user-images.githubusercontent.com/17212107/48951522-9e13fc00-ef1d-11e8-9e8b-984061199e8c.png)

**Comment by KazeJiyu** [comment]
Thank you for your feedbacks, maybe that the issue do comes from the OS, after all.

I just released the new `1.0.1` version as an attempt to solve the problem ; could you update your installation and then tell me whether the bug has been fixed ?

You can update the plug-in from either:
- `Help` > `Check for Updates`

or:
- `Help` > `Install new Software...` > `https://dl.bintray.com/kazejiyu/eclipse-discord-integration/updates/`

**Comment by CleusGamer201** [comment]
yes it works perfectly, i have open eclipse a installed the plugin again later that i close eclipse and open it and check if work the discord rich presence and later i have closed eclipse and the presence has left and eclipse no have any process in the task manager. Thanks for the fix <3

**Comment by KazeJiyu** [comment]
Fixed by PR #57
