### ISSUE TITLE
Discord not showing Eclipse IDE properly

### ISSUE THREAD

**Issue by OmgItzValk** [KazeJiyu/eclipse-discord-integration#58]
This is what it looks like on discord 
![capture 3](https://user-images.githubusercontent.com/44910972/49162592-18c88700-f323-11e8-89b4-fd4023863dea.PNG)

My Eclipse IDE version
![capture](https://user-images.githubusercontent.com/44910972/49162611-254cdf80-f323-11e8-8366-f8a23dfc77ef.PNG)

My error log
![capture 2](https://user-images.githubusercontent.com/44910972/49162628-2d0c8400-f323-11e8-99b4-24d728608043.PNG)

I am also using Windows 10. Not sure why this is occurring because it worked the first day I got it, but now when I open Eclipse IDE this is how it shows up (and I didn't change any settings or whatever after I first got this discord integration). 

Thanks in advance

**Comment by KazeJiyu** [comment]
Issue #56 has been closed with the new `1.0.3` release so I close this one as well. Please leave a comment on the other thread is the issue has not been solved.
