### ISSUE TITLE
Error while downloading extension

### ISSUE THREAD

**Issue by Des7165** [KazeJiyu/eclipse-discord-integration#93]
## When i try to download the extension on  eclipse 2019-03-win32-x86_64 i get an error where it says the repository cant be found

I get the following error:

Unable to read repository at https://echebbi.github.io/eclipse-discord-integration-updates/releases/1.2.2/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

When i try to download other extensions this error doesnt occur.

- **Plug-in version**: latest
- **Eclipse IDE version**: eclipse 2019-03-win32-x86_64

**Comment by echebbi** [comment]
Hello, sorry for the late answer. I can't reproduce your issue so it might be specific to your environment. Are you trying to install the plug-in on a computer that is behind a corporate proxy/firewall? If that's the case your issue should be solved by this StackOverflow thread: https://stackoverflow.com/q/40667733/10226142. Could you try one of the answer?

**Comment by Mailaender** [comment]
I also can't download the plugin. Probably because of the JFrog Bintray shutdown?

**Comment by echebbi** [comment]
I moved the repository, it has been on GitHub since May 4th so the issue doesn't come from JFrog.

I can install the plug-in without problem, and the Markeplace Client reports as much downloads as usual. Have you tried to install the plug-in from the Eclipse Marketplace or directly from the p2 link? Also @Mailaender what error did you get exactly?

**Comment by Mailaender** [comment]
https://dl.bintray.com/kazejiyu/eclipse-discord-integration/ said forbidden.

**Comment by echebbi** [comment]
Yes, the repository is not on Bintray anymore. Use https://echebbi.github.io/eclipse-discord-integration-updates/releases/1.2.2 instead.
